title: Time Machine theme
description: Time Machine is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-time-machine
github:
  zip_url: http://example.com/download.zip
  another_url: another value
